/** The remaining Direction A patterns. A specimen is never a live service. */
export const designTemplates = [
  { id: 'topic', family: 'Discover', name: 'Topic hub', title: 'Home insurance.', description: 'Understand the coverage. Explore the questions. Check the sources.', states: ['Browse', 'Filtered', 'No matches'], next: 'Apply the shared browse frame to live coverage and question indexes.' },
  { id: 'industry', family: 'Discover', name: 'Industry hub', title: 'Insurance for your business.', description: 'Start with your work, then follow the research that matters to it.', states: ['Industry context', 'Related questions', 'Coverage links'], next: 'Use the existing industry taxonomy and source-read content, not generated recommendations.' },
  { id: 'state', family: 'Discover', name: 'State hub', title: 'California insurance.', description: 'Local questions, coverage guides, and the original records behind them.', states: ['Jurisdiction context', 'Research filter', 'Official-source rail'], next: 'Apply the jurisdiction template to the existing state records.' },
  { id: 'coverage', family: 'Read', name: 'Coverage guide', title: 'Homeowners insurance.', description: 'A clear reading frame for definitions, coverage parts, and policy limitations.', states: ['Overview', 'Coverage parts', 'Exclusions', 'Source inspection'], next: 'Migrate the existing coverage template without changing or shortening its cited claims.' },
  { id: 'case-study', family: 'Read', name: 'Case study', title: 'Follow the reasoning.', description: 'What happened, what turned on it, and what cannot be generalized.', states: ['Provenance', 'Record context', 'Reasoning', 'Limits'], next: 'Apply the reading frame to the existing labeled examples and retain their provenance.' },
  { id: 'source', family: 'Read', name: 'Source record', title: 'Behind the answer.', description: 'One document, the statements it supports, and its place in the research.', states: ['Document identity', 'Claim addresses', 'Reading history'], next: 'Migrate source records while preserving claim IDs, checksums, and canonical links.' },
  { id: 'contributor', family: 'Personal', name: 'Contributor profile', title: 'Your work. In context.', description: 'A public profile built around original contributions and documented expertise.', states: ['Profile', 'Work empty state', 'Credential scope'], next: 'Connect verified credential records and authored publications; never manufacture either.' },
  { id: 'saved', family: 'Personal', name: 'Saved and following', title: 'Your library.', description: 'Keep the research you want to come back to.', states: ['Example collection', 'Remove and undo', 'Empty', 'Following', 'Preferences'], next: 'Connect account-scoped saves and explicit update preferences after invited auth passes.' },
  { id: 'your-coverage', family: 'Personal', name: 'Private coverage', title: 'Your coverage. Your choice.', description: 'Understand what a policy connection would share before connecting anything.', states: ['Unconnected', 'Consent preview', 'Field review', 'Cancelled'], next: 'Privacy and security review, then Canopy sandbox; no document or credential intake here.' },
  { id: 'tools', family: 'Discover', name: 'Tool launcher', title: 'Make the next step clearer.', description: 'Choose a task. Use a focused worksheet. Keep the source close.', states: ['Choose a task', 'Worksheet explanation', 'Open existing tool'], next: 'Apply the tool frame to existing local worksheets without changing their decision rules.' },
  { id: 'company-partner', family: 'Contribute', name: 'Company representative', title: 'Add your company\'s perspective.', description: 'Explain a process, respond with context, and help readers find official information.', states: ['Role requirements', 'Response boundaries', 'Access closed'], next: 'Organization authorization and scoped representative permissions, separate from identity or policy checks.' },
  { id: 'research-desk', family: 'Operations', name: 'Research workspace', title: 'Research desk.', description: 'From a question gap to an evidence packet, with a human decision at the end.', states: ['Candidate queue', 'Source inspection', 'Conflict', 'Provider failure'], next: 'Connect the existing bounded scout and durable task store. Keep publication gated.' },
  { id: 'moderation', family: 'Operations', name: 'Moderation workspace', title: 'Review with context.', description: 'A careful decision starts with the original account, its evidence, and its history.', states: ['Example report', 'Privacy', 'Response dispute', 'Decision preview'], next: 'Bind to the existing moderation roles, audit events, withdrawal, and appeal routes.' },
  { id: 'standards', family: 'Read', name: 'About and standards', title: 'Trust comes from the details.', description: 'How Birch separates research, experience, and the people behind both.', states: ['Standards', 'Operator disclosure', 'Corrections', 'Contact paths'], next: 'Reuse this navigation-led editorial template for methodology, about, privacy, and terms.' },
] as const;
export type DesignTemplate = typeof designTemplates[number];
export type DesignTemplateId = DesignTemplate['id'];
