/** Design contracts, not promises that the service behind a specimen is live. */
export const pagePatterns = [
  { group: 'Discover', title: 'Landing', href: '/', action: 'Ask Birch', pattern: 'Selected A / Focus: one question composer, short starting points, and a working product preview.', state: 'Selected / implemented', next: 'Test comprehension and successful question starts.' },
  { group: 'Discover', title: 'Answer', href: '/questions/replacement-cost-vs-market-value', action: 'Read and check sources', pattern: 'Short answer, scope, inline citations, source drawer, section navigation, citation export.', state: 'Implemented', next: 'Extend the reading pattern to coverage, state, and case-study pages.' },
  { group: 'Discover', title: 'Coverage / industry / state', href: '/design/templates/topic', action: 'Explore this topic', pattern: 'Shared browse frame with existing records, real counts, record-type filtering, search, and an empty state. Separate industry and state specimens.', state: 'Interactive templates', next: 'Apply the approved frames to the existing public routes without changing research.' },
  { group: 'Discover', title: 'Company directory', href: '/companies', action: 'Find a company', pattern: 'Search first; distinguish a group, brand, legal insurer, regulator, and program.', state: 'Implemented', next: 'Add sourced insurer entities and brand-to-entity mapping.' },
  { group: 'Discover', title: 'Company profile', href: '/companies/farmers-insurance-exchange', action: 'Ask about this company', pattern: 'Identity, coverage, community, sources. A facts rail and contextual actions.', state: 'Implemented', next: 'Connect coverage forms, dated figures, and community subjects.' },
  { group: 'Discuss', title: 'Community / topic forum', href: '/design/commons-preview', action: 'Prepare a contribution', pattern: 'Topic navigation, readable thread rows, working type/search filters, and contextual research links.', state: 'Design preview', next: 'Connect the existing thread store after deployment readiness.' },
  { group: 'Discuss', title: 'Thread / company response', href: '/design/thread-preview', action: 'Reply', pattern: 'Original account, replies, related research. Explicit professional and company roles.', state: 'Design preview', next: 'Role-scoped responses, author resolution, reporting, and revision history.' },
  { group: 'Discuss', title: 'Structured experience', href: '/contribute', action: 'Preview contribution', pattern: 'Choose a type, write, inspect the private preview, and return to editing. Nothing is stored or submitted.', state: 'Local interactive preview', next: 'Company/state/timeline fields and existing moderated intake after readiness.' },
  { group: 'Contribute', title: 'Professional profile', href: '/design/templates/contributor', action: 'Prepare research', pattern: 'Authored work, credential scope, and disclosure tabs; an honest empty profile with no invented person or verification.', state: 'Interactive template', next: 'Connect actual credential and publication records after account readiness.' },
  { group: 'Contribute', title: 'Article / research composer', href: '/contribute', action: 'Preview contribution', pattern: 'Research-specific guidance, original explanation, source notes, privacy check, and text-only preview.', state: 'Local interactive preview', next: 'Connect existing authenticated drafts, disclosures, and moderation; no automatic publication.' },
  { group: 'Account', title: 'Sign-in / verification', href: '/design/account-preview', action: 'Email me a link', pattern: 'One field; check email; expired link; resend; return to the initiating action.', state: 'Interactive preview + app code', next: 'Exercise real mail, durable storage, abuse limits, and invited accounts.' },
  { group: 'Account', title: 'Saved research / following', href: '/design/templates/saved', action: 'Return to research', pattern: 'Example library, remove and undo, empty collection, following, and explicit email preferences.', state: 'Local interactive template', next: 'Connect account-scoped records; choices in this specimen are not saved.' },
  { group: 'Account', title: 'Your coverage', href: '/design/templates/your-coverage', action: 'Preview shared fields', pattern: 'Unconnected, optional field selection, review, edit, and cancel-and-clear. No credentials or documents accepted.', state: 'Consent design only', next: 'Canopy sandbox and reviewed consent, revocation, deletion, and privacy/security boundaries.' },
  { group: 'Tools', title: 'Guided worksheet', href: '/design/templates/tools', action: 'Open worksheet', pattern: 'Task-first launcher with progressive disclosure and links to real existing worksheets.', state: 'Template + existing tools', next: 'Migrate each worksheet input/result frame without altering its decision rules.' },
  { group: 'Operations', title: 'Research intake / reviewer', href: '/design/templates/research-desk', action: 'Inspect the evidence', pattern: 'Selectable candidate, scope conflict, and provider failure scenarios. Local checklist and explicit publication gate.', state: 'Interactive template', next: 'Durable jobs, fetched-source validation, cost caps, and authorized human review.' },
  { group: 'Operations', title: 'Moderation / corrections', href: '/design/templates/moderation', action: 'Review context', pattern: 'Privacy report, response dispute, and correction scenarios. Decision preview does not perform an action.', state: 'Interactive template', next: 'Bind existing permissions, human review, notifications, appeals, and audit events.' },
] as const;

export const interactionRules = [
  ['Navigation', 'Icons plus labels; pointer hover and keyboard open; Escape restores focus; tap toggles.'],
  ['Buttons', '44px minimum target; 120-180ms color/press feedback; one primary action in each section.'],
  ['Sources', 'Inline citations open a source drawer on answer and company pages. Escape returns focus; permanent source anchors remain the no-JavaScript fallback.'],
  ['Tabs and sections', 'View tabs use arrow keys and visible selection. Record sections use ordinary keyboard-focusable links with meaningful deep links.'],
  ['Reading', '65-75 characters per line; sources at right on desktop and below on mobile; steady text.'],
  ['Motion', 'Only navigation and state changes move. Respect reduced motion. Never delay an answer for an effect.'],
  ['Engagement', 'Saved research, followed topics, useful replies, and corrections. No fabricated activity or posting streaks.'],
  ['Unknowns', 'Say what is missing; provide a next action. Never make a failed research request look complete.'],
] as const;
