/** Design contracts, not promises that the service behind a specimen is live. */
export const pagePatterns = [
  { group: 'Discover', title: 'Landing', href: '/design/directions/focus', action: 'Ask Birch', pattern: 'One question composer; short starting points; a working product preview.', state: 'Implemented', next: 'Test comprehension and successful question starts.' },
  { group: 'Discover', title: 'Answer', href: '/questions/replacement-cost-vs-market-value', action: 'Read and check sources', pattern: 'Short answer, scope, inline citations, source drawer, section navigation, citation export.', state: 'Implemented', next: 'Extend the reading pattern to coverage, state, and case-study pages.' },
  { group: 'Discover', title: 'Coverage / industry / state', href: '/industries', action: 'Explore this topic', pattern: 'A shared topic header, useful questions, guides, cases, and tools.', state: 'Existing research', next: 'One topic template with jurisdiction and audience filters.' },
  { group: 'Discover', title: 'Company directory', href: '/companies', action: 'Find a company', pattern: 'Search first; distinguish a group, brand, legal insurer, regulator, and program.', state: 'Implemented', next: 'Add sourced insurer entities and brand-to-entity mapping.' },
  { group: 'Discover', title: 'Company profile', href: '/companies/farmers-insurance-exchange', action: 'Ask about this company', pattern: 'Identity, coverage, community, sources. A facts rail and contextual actions.', state: 'Implemented', next: 'Connect coverage forms, dated figures, and community subjects.' },
  { group: 'Discuss', title: 'Community / topic forum', href: '/design/commons-preview', action: 'Ask the community', pattern: 'Topic navigation, readable thread rows, useful filters, quiet follow control.', state: 'Design preview', next: 'Connect the existing thread store after deployment readiness.' },
  { group: 'Discuss', title: 'Thread / company response', href: '/design/thread-preview', action: 'Reply', pattern: 'Original account, replies, related research. Explicit professional and company roles.', state: 'Design preview', next: 'Role-scoped responses, author resolution, reporting, and revision history.' },
  { group: 'Discuss', title: 'Structured experience', href: '/contribute', action: 'Preview my experience', pattern: 'Company, coverage, state, timeline, what happened, outcome, disclosure.', state: 'Gated draft flow', next: 'Evidence relationship badges, privacy preview, and moderation routing.' },
  { group: 'Contribute', title: 'Professional profile', href: '/professionals', action: 'Contribute your expertise', pattern: 'Credential scope, topics, original publications, disclosed affiliations, external profile.', state: 'Entry page exists', next: 'Design the public author page and scoped credential status.' },
  { group: 'Contribute', title: 'Article / research composer', href: '/contribute', action: 'Submit for review', pattern: 'Purpose, scope, claim-source pairs, original analysis, conflicts, preview.', state: 'Gated draft flow', next: 'Autosaved private drafts, reviewer comments, revision requests, publication history.' },
  { group: 'Account', title: 'Sign-in / verification', href: '/design/account-preview', action: 'Email me a link', pattern: 'One field; check email; expired link; resend; return to the initiating action.', state: 'Interactive preview + app code', next: 'Exercise real mail, durable storage, abuse limits, and invited accounts.' },
  { group: 'Account', title: 'Saved research / following', href: '/design/component-states', action: 'Save', pattern: 'Save an answer or follow a topic when it becomes useful; explicit confirmation.', state: 'Planned', next: 'Design empty, saved, removed, signed-out, and email preference states.' },
  { group: 'Account', title: 'Your coverage', href: '/lens', action: 'Connect a policy', pattern: 'Optional private connection, permitted fields, confirmation, revoke, deletion.', state: 'Local text preview only', next: 'Canopy sandbox and a reviewed privacy/security design before document intake.' },
  { group: 'Tools', title: 'Guided worksheet', href: '/tools/policy-comparison', action: 'Compare the details', pattern: 'One step at a time; explain each field; source-linked result; printable summary.', state: 'Local tools exist', next: 'Unify input and result layouts, progress, empty, and error states.' },
  { group: 'Operations', title: 'Research intake / reviewer', href: '/design/research-pipeline-preview', action: 'Review the evidence', pattern: 'Question gaps, candidate sources, supported claims, conflicts, human review.', state: 'Provider contract exists', next: 'Durable jobs, fetched-source validation, cost caps, and provider failure states.' },
  { group: 'Operations', title: 'Moderation / corrections', href: '/design/reviewer-console-preview', action: 'Resolve review', pattern: 'Report reason, contextual evidence, decision, appeal, and visible history.', state: 'App code + preview', next: 'Exercise permissions and human review with seeded test cases.' },
] as const;

export const interactionRules = [
  ['Navigation', 'Icons plus labels; pointer hover and keyboard open; Escape restores focus; tap toggles.'],
  ['Buttons', '44px minimum target; 120-180ms color/press feedback; one primary action in each section.'],
  ['Sources', 'Inline citations open a source drawer on answer and company pages. Escape returns focus; permanent source anchors remain the no-JavaScript fallback.'],
  ['Tabs and sections', 'View tabs use arrow keys and visible selection. Record sections use ordinary keyboard-focusable links with meaningful deep links.'],
  ['Reading', '65-75 characters per line; sources at right on desktop and below on mobile; steady text.'],
  ['Motion', 'Only navigation and state changes move. Respect reduced motion. Never delay an answer for an effect.'],
  ['Engagement', 'Saved research, followed topics, useful replies, and corrections. No fabricated activity or posting streaks.'],
  ['Unknowns', 'Say what is missing; provide a next action. Never make a failed research request look complete.'],
] as const;
