/* GENERATED by scripts/sync-subjects.mjs. Do not edit by hand.
 *
 * What a thread may be about: exactly what the evidence layer publishes.
 * Regenerate after adding a company, coverage or question record - the
 * suite fails the build when this file is stale.
 */
import type { Subject } from './threads';

export const GENERATED_SUBJECTS: Subject[] = [
	{
		"id": "company:california-department-of-insurance",
		"kind": "company",
		"name": "California Department of Insurance",
		"recordPath": "/companies/california-department-of-insurance"
	},
	{
		"id": "company:california-earthquake-authority",
		"kind": "company",
		"name": "California Earthquake Authority",
		"recordPath": "/companies/california-earthquake-authority"
	},
	{
		"id": "company:naic",
		"kind": "company",
		"name": "National Association of Insurance Commissioners",
		"recordPath": "/companies/naic"
	},
	{
		"id": "coverage:commercial-auto",
		"kind": "coverage",
		"name": "Commercial Auto Insurance",
		"recordPath": "/insurance/commercial-auto"
	},
	{
		"id": "coverage:commercial-general-liability",
		"kind": "coverage",
		"name": "Commercial General Liability (CGL)",
		"recordPath": "/insurance/commercial-general-liability"
	},
	{
		"id": "coverage:commercial-property",
		"kind": "coverage",
		"name": "Commercial Property Insurance",
		"recordPath": "/insurance/commercial-property"
	},
	{
		"id": "coverage:community-association-california",
		"kind": "coverage",
		"name": "Community association insurance (California)",
		"recordPath": "/insurance/community-association-california"
	},
	{
		"id": "coverage:condominium-unit-owners-california",
		"kind": "coverage",
		"name": "Condominium unit owners insurance (California)",
		"recordPath": "/insurance/condominium-unit-owners-california"
	},
	{
		"id": "coverage:cyber-liability",
		"kind": "coverage",
		"name": "Cyber liability and privacy",
		"recordPath": "/insurance/cyber-liability"
	},
	{
		"id": "coverage:directors-and-officers-california",
		"kind": "coverage",
		"name": "Directors and officers liability (California)",
		"recordPath": "/insurance/directors-and-officers-california"
	},
	{
		"id": "coverage:employer-group-health-federal",
		"kind": "coverage",
		"name": "Employer group health coverage (federal requirements)",
		"recordPath": "/insurance/employer-group-health-federal"
	},
	{
		"id": "coverage:employment-practices-liability",
		"kind": "coverage",
		"name": "Employment practices liability",
		"recordPath": "/insurance/employment-practices-liability"
	},
	{
		"id": "coverage:flood-nfip",
		"kind": "coverage",
		"name": "Flood insurance (National Flood Insurance Program)",
		"recordPath": "/insurance/flood-nfip"
	},
	{
		"id": "coverage:homeowners",
		"kind": "coverage",
		"name": "Homeowners insurance",
		"recordPath": "/insurance/homeowners"
	},
	{
		"id": "coverage:individual-life-california",
		"kind": "coverage",
		"name": "Individual life insurance (California)",
		"recordPath": "/insurance/individual-life-california"
	},
	{
		"id": "coverage:inland-marine",
		"kind": "coverage",
		"name": "Inland marine",
		"recordPath": "/insurance/inland-marine"
	},
	{
		"id": "coverage:landlord-rental-dwelling",
		"kind": "coverage",
		"name": "Landlord / rental dwelling insurance",
		"recordPath": "/insurance/landlord-rental-dwelling"
	},
	{
		"id": "coverage:medical-professional-liability-california",
		"kind": "coverage",
		"name": "Medical professional liability (California)",
		"recordPath": "/insurance/medical-professional-liability-california"
	},
	{
		"id": "coverage:motor-truck-cargo",
		"kind": "coverage",
		"name": "Motor truck cargo",
		"recordPath": "/insurance/motor-truck-cargo"
	},
	{
		"id": "coverage:personal-auto-california",
		"kind": "coverage",
		"name": "Personal auto insurance (California)",
		"recordPath": "/insurance/personal-auto-california"
	},
	{
		"id": "coverage:professional-liability",
		"kind": "coverage",
		"name": "Professional liability (claims-made)",
		"recordPath": "/insurance/professional-liability"
	},
	{
		"id": "coverage:renters-california",
		"kind": "coverage",
		"name": "Renters insurance (California)",
		"recordPath": "/insurance/renters-california"
	},
	{
		"id": "coverage:residential-earthquake-california",
		"kind": "coverage",
		"name": "Residential earthquake insurance (California)",
		"recordPath": "/insurance/residential-earthquake-california"
	},
	{
		"id": "coverage:scheduled-personal-property-california",
		"kind": "coverage",
		"name": "Scheduled personal property (California)",
		"recordPath": "/insurance/scheduled-personal-property-california"
	},
	{
		"id": "coverage:surety-bonds",
		"kind": "coverage",
		"name": "Surety bonds",
		"recordPath": "/insurance/surety-bonds"
	},
	{
		"id": "coverage:surplus-lines-california",
		"kind": "coverage",
		"name": "Surplus lines (California)",
		"recordPath": "/insurance/surplus-lines-california"
	},
	{
		"id": "coverage:title-insurance-california",
		"kind": "coverage",
		"name": "Title insurance (California)",
		"recordPath": "/insurance/title-insurance-california"
	},
	{
		"id": "coverage:wildfire-california",
		"kind": "coverage",
		"name": "Wildfire coverage and availability (California)",
		"recordPath": "/insurance/wildfire-california"
	},
	{
		"id": "coverage:windstorm-texas",
		"kind": "coverage",
		"name": "Windstorm and hail (Texas)",
		"recordPath": "/insurance/windstorm-texas"
	},
	{
		"id": "coverage:workers-compensation-california",
		"kind": "coverage",
		"name": "Workers Compensation Insurance (California)",
		"recordPath": "/insurance/workers-compensation-california"
	},
	{
		"id": "question:am-i-an-applicable-large-employer",
		"kind": "question",
		"name": "How is the 50-employee health coverage threshold actually counted?",
		"recordPath": "/questions/am-i-an-applicable-large-employer"
	},
	{
		"id": "question:am-i-eligible-for-citizens-florida",
		"kind": "question",
		"name": "Can I insure my Florida home with Citizens, and what actually makes me eligible?",
		"recordPath": "/questions/am-i-eligible-for-citizens-florida"
	},
	{
		"id": "question:am-i-eligible-for-twia-and-what-is-a-wpi-8",
		"kind": "question",
		"name": "Am I eligible for Texas windstorm coverage, and what is a WPI-8?",
		"recordPath": "/questions/am-i-eligible-for-twia-and-what-is-a-wpi-8"
	},
	{
		"id": "question:auto-policy-cancelled-mid-term-california",
		"kind": "question",
		"name": "My car insurance was cancelled in the middle of the policy term. Was the insurer allowed to do that?",
		"recordPath": "/questions/auto-policy-cancelled-mid-term-california"
	},
	{
		"id": "question:auto-policy-not-renewed-california",
		"kind": "question",
		"name": "My auto insurer says it will not renew my policy. What is it required to do, and how long do I have?",
		"recordPath": "/questions/auto-policy-not-renewed-california"
	},
	{
		"id": "question:business-closed-but-nothing-damaged-does-it-pay",
		"kind": "question",
		"name": "My business had to close but nothing was physically damaged. Does business income coverage pay?",
		"recordPath": "/questions/business-closed-but-nothing-damaged-does-it-pay"
	},
	{
		"id": "question:claiming-on-a-contractor-license-bond-california",
		"kind": "question",
		"name": "How do I make a claim against a contractor's licence bond, and what else should I file at the same time?",
		"recordPath": "/questions/claiming-on-a-contractor-license-bond-california"
	},
	{
		"id": "question:claims-made-retroactive-date",
		"kind": "question",
		"name": "What is a claims-made retroactive date?",
		"recordPath": "/questions/claims-made-retroactive-date"
	},
	{
		"id": "question:commercial-auto-covered-auto-symbols",
		"kind": "question",
		"name": "What do the numbers next to the coverages on my commercial auto policy mean?",
		"recordPath": "/questions/commercial-auto-covered-auto-symbols"
	},
	{
		"id": "question:commercial-property-underwriting-information",
		"kind": "question",
		"name": "What information does a commercial property underwriter usually request?",
		"recordPath": "/questions/commercial-property-underwriting-information"
	},
	{
		"id": "question:complaint-about-a-california-insurer-where-it-goes",
		"kind": "question",
		"name": "I have a complaint about my home insurer. Where does it go, and what does the regulator actually do with it?",
		"recordPath": "/questions/complaint-about-a-california-insurer-where-it-goes"
	},
	{
		"id": "question:contract-additional-insured-status",
		"kind": "question",
		"name": "When can a contract require additional insured status?",
		"recordPath": "/questions/contract-additional-insured-status"
	},
	{
		"id": "question:contractor-license-bond-what-it-pays-california",
		"kind": "question",
		"name": "My contractor is licensed and bonded. If the work is defective, what will the bond actually pay me?",
		"recordPath": "/questions/contractor-license-bond-what-it-pays-california"
	},
	{
		"id": "question:customer-harasses-my-employee-liability-california",
		"kind": "question",
		"name": "Can my business be liable if a customer harasses one of my employees?",
		"recordPath": "/questions/customer-harasses-my-employee-liability-california"
	},
	{
		"id": "question:did-florida-repeal-no-fault",
		"kind": "question",
		"name": "Did Florida repeal no-fault insurance?",
		"recordPath": "/questions/did-florida-repeal-no-fault"
	},
	{
		"id": "question:does-renters-insurance-cover-earthquake-or-flood-california",
		"kind": "question",
		"name": "Does renters insurance cover earthquake or flood in California?",
		"recordPath": "/questions/does-renters-insurance-cover-earthquake-or-flood-california"
	},
	{
		"id": "question:does-title-insurance-cover-future-problems-california",
		"kind": "question",
		"name": "Does title insurance cover problems that arise after I buy the house?",
		"recordPath": "/questions/does-title-insurance-cover-future-problems-california"
	},
	{
		"id": "question:does-twia-cover-storm-surge",
		"kind": "question",
		"name": "A hurricane damaged my house. Does my Texas windstorm policy cover the storm surge?",
		"recordPath": "/questions/does-twia-cover-storm-surge"
	},
	{
		"id": "question:earthquake-cover-for-a-mobilehome-california",
		"kind": "question",
		"name": "I live in a mobilehome. Can I get earthquake cover, and what does the policy look like?",
		"recordPath": "/questions/earthquake-cover-for-a-mobilehome-california"
	},
	{
		"id": "question:employee-driving-own-car-for-work-coverage",
		"kind": "question",
		"name": "Does my business auto policy cover an employee driving their own car for work?",
		"recordPath": "/questions/employee-driving-own-car-for-work-coverage"
	},
	{
		"id": "question:flood-insurance-basement-contents",
		"kind": "question",
		"name": "Is anything in my basement covered by flood insurance?",
		"recordPath": "/questions/flood-insurance-basement-contents"
	},
	{
		"id": "question:flood-insurance-living-expenses",
		"kind": "question",
		"name": "Does flood insurance pay for somewhere to live while my home is repaired?",
		"recordPath": "/questions/flood-insurance-living-expenses"
	},
	{
		"id": "question:florida-minimum-auto-insurance-and-after-dui",
		"kind": "question",
		"name": "What auto insurance does Florida require, and what changes after a DUI?",
		"recordPath": "/questions/florida-minimum-auto-insurance-and-after-dui"
	},
	{
		"id": "question:florida-pip-what-it-pays",
		"kind": "question",
		"name": "What does Florida PIP actually pay, and what is the 14-day rule?",
		"recordPath": "/questions/florida-pip-what-it-pays"
	},
	{
		"id": "question:free-look-return-life-policy-annuity-california",
		"kind": "question",
		"name": "Can I return a life policy or annuity after buying it, and do I get everything back?",
		"recordPath": "/questions/free-look-return-life-policy-annuity-california"
	},
	{
		"id": "question:general-liability-vs-professional-liability",
		"kind": "question",
		"name": "What is the difference between general liability and professional liability?",
		"recordPath": "/questions/general-liability-vs-professional-liability"
	},
	{
		"id": "question:good-driver-discount-california",
		"kind": "question",
		"name": "Do I qualify for California's Good Driver Discount, and what is it actually worth?",
		"recordPath": "/questions/good-driver-discount-california"
	},
	{
		"id": "question:hoa-master-policy-covers-my-unit-california",
		"kind": "question",
		"name": "Does my HOA's master policy cover the inside of my unit?",
		"recordPath": "/questions/hoa-master-policy-covers-my-unit-california"
	},
	{
		"id": "question:hoa-must-notify-members-coverage-cut-california",
		"kind": "question",
		"name": "Does my HOA have to tell members if its insurance was cancelled or cut back?",
		"recordPath": "/questions/hoa-must-notify-members-coverage-cut-california"
	},
	{
		"id": "question:homeowners-earthquake-california",
		"kind": "question",
		"name": "Does homeowners insurance cover earthquake damage in California?",
		"recordPath": "/questions/homeowners-earthquake-california"
	},
	{
		"id": "question:how-a-cea-policy-is-actually-bought-and-serviced",
		"kind": "question",
		"name": "The California Earthquake Authority is a state body. So why does buying its policy go through my own insurer?",
		"recordPath": "/questions/how-a-cea-policy-is-actually-bought-and-serviced"
	},
	{
		"id": "question:how-a-commercial-property-loss-is-valued",
		"kind": "question",
		"name": "How does a commercial property policy value a loss, and what is coinsurance actually doing to my payment?",
		"recordPath": "/questions/how-a-commercial-property-loss-is-valued"
	},
	{
		"id": "question:how-business-income-coverage-measures-what-it-pays",
		"kind": "question",
		"name": "How does business income coverage work out what it pays, and when does the clock start and stop?",
		"recordPath": "/questions/how-business-income-coverage-measures-what-it-pays"
	},
	{
		"id": "question:how-california-decides-what-auto-insurers-may-charge",
		"kind": "question",
		"name": "How does California decide what my auto insurer is allowed to charge me?",
		"recordPath": "/questions/how-california-decides-what-auto-insurers-may-charge"
	},
	{
		"id": "question:how-general-liability-limits-work",
		"kind": "question",
		"name": "My general liability policy shows several different limits. How do they actually work together?",
		"recordPath": "/questions/how-general-liability-limits-work"
	},
	{
		"id": "question:how-long-to-elect-cobra-continuation",
		"kind": "question",
		"name": "How long do I have to elect COBRA continuation after losing coverage?",
		"recordPath": "/questions/how-long-to-elect-cobra-continuation"
	},
	{
		"id": "question:how-long-to-file-a-freight-damage-claim",
		"kind": "question",
		"name": "My freight arrived damaged. Who do I claim against, and how long do I have?",
		"recordPath": "/questions/how-long-to-file-a-freight-damage-claim"
	},
	{
		"id": "question:how-long-to-file-employment-claim-california",
		"kind": "question",
		"name": "How long does someone have to file an employment discrimination claim in California?",
		"recordPath": "/questions/how-long-to-file-employment-claim-california"
	},
	{
		"id": "question:how-much-fidelity-insurance-must-an-hoa-carry-california",
		"kind": "question",
		"name": "How much crime or fidelity insurance must a California HOA carry?",
		"recordPath": "/questions/how-much-fidelity-insurance-must-an-hoa-carry-california"
	},
	{
		"id": "question:how-to-check-a-california-insurer-and-agent-before-you-buy",
		"kind": "question",
		"name": "Before I buy a California home insurance policy, what can I actually check about the insurer and the agent?",
		"recordPath": "/questions/how-to-check-a-california-insurer-and-agent-before-you-buy"
	},
	{
		"id": "question:inland-marine-uses",
		"kind": "question",
		"name": "What is inland marine insurance used for?",
		"recordPath": "/questions/inland-marine-uses"
	},
	{
		"id": "question:insurer-choose-repair-shop-california",
		"kind": "question",
		"name": "Can my insurer make me use their repair shop after a California car accident?",
		"recordPath": "/questions/insurer-choose-repair-shop-california"
	},
	{
		"id": "question:is-the-california-malpractice-cap-still-250000",
		"kind": "question",
		"name": "Everything I read says California caps medical malpractice damages at $250,000. Is that still the number?",
		"recordPath": "/questions/is-the-california-malpractice-cap-still-250000"
	},
	{
		"id": "question:landlord-insurance-does-not-cover-my-things-california",
		"kind": "question",
		"name": "My landlord has insurance on the building. Does it cover my belongings?",
		"recordPath": "/questions/landlord-insurance-does-not-cover-my-things-california"
	},
	{
		"id": "question:landlord-policy-vs-homeowners",
		"kind": "question",
		"name": "When does a landlord need a landlord policy instead of homeowners coverage?",
		"recordPath": "/questions/landlord-policy-vs-homeowners"
	},
	{
		"id": "question:lender-insurance-requirement",
		"kind": "question",
		"name": "What does a lender insurance requirement actually prove?",
		"recordPath": "/questions/lender-insurance-requirement"
	},
	{
		"id": "question:life-policy-lapsed-missed-payment-california",
		"kind": "question",
		"name": "My life insurance lapsed because I missed a payment. Was the insurer allowed to do that?",
		"recordPath": "/questions/life-policy-lapsed-missed-payment-california"
	},
	{
		"id": "question:miller-act-payment-bond-deadlines",
		"kind": "question",
		"name": "How long do I have to claim on a payment bond for unpaid work on a federal job?",
		"recordPath": "/questions/miller-act-payment-bond-deadlines"
	},
	{
		"id": "question:must-i-carry-workers-comp-california",
		"kind": "question",
		"name": "Do I have to carry workers' compensation in California, and what are my options if I do?",
		"recordPath": "/questions/must-i-carry-workers-comp-california"
	},
	{
		"id": "question:must-i-cover-officers-and-owners-california",
		"kind": "question",
		"name": "Do I have to carry workers' compensation for my corporate officers and owners?",
		"recordPath": "/questions/must-i-cover-officers-and-owners-california"
	},
	{
		"id": "question:nonrenewal-after-wildfire-moratorium-california",
		"kind": "question",
		"name": "My home was not damaged, but my insurer is not renewing after a nearby wildfire. Is that allowed?",
		"recordPath": "/questions/nonrenewal-after-wildfire-moratorium-california"
	},
	{
		"id": "question:replacement-cost-vs-market-value",
		"kind": "question",
		"name": "What is the difference between replacement cost and market value?",
		"recordPath": "/questions/replacement-cost-vs-market-value"
	},
	{
		"id": "question:same-limit-different-protection",
		"kind": "question",
		"name": "Why can two insurance policies with the same limit protect differently?",
		"recordPath": "/questions/same-limit-different-protection"
	},
	{
		"id": "question:schedule-valuables-or-separate-floater",
		"kind": "question",
		"name": "Should I schedule valuables on my homeowners policy or buy a separate floater?",
		"recordPath": "/questions/schedule-valuables-or-separate-floater"
	},
	{
		"id": "question:sued-personally-for-hoa-common-area-california",
		"kind": "question",
		"name": "Can I be sued personally because I own a share of my HOA's common area?",
		"recordPath": "/questions/sued-personally-for-hoa-common-area-california"
	},
	{
		"id": "question:surety-bond-vs-insurance",
		"kind": "question",
		"name": "What does a surety bond guarantee, and how is it different from insurance?",
		"recordPath": "/questions/surety-bond-vs-insurance"
	},
	{
		"id": "question:surplus-lines-guarantee-fund-california",
		"kind": "question",
		"name": "Does a California guarantee fund cover my surplus lines policy if the insurer fails?",
		"recordPath": "/questions/surplus-lines-guarantee-fund-california"
	},
	{
		"id": "question:surplus-lines-premium-tax-california",
		"kind": "question",
		"name": "There is a surplus lines tax on my policy. What is it, and who is actually required to pay it?",
		"recordPath": "/questions/surplus-lines-premium-tax-california"
	},
	{
		"id": "question:texas-minimum-auto-and-what-you-carry-by-default",
		"kind": "question",
		"name": "What auto insurance does Texas require, and what am I carrying that I never asked for?",
		"recordPath": "/questions/texas-minimum-auto-and-what-you-carry-by-default"
	},
	{
		"id": "question:three-declinations-before-surplus-lines-california",
		"kind": "question",
		"name": "How many insurers have to decline before a broker can place my risk in the non-admitted market?",
		"recordPath": "/questions/three-declinations-before-surplus-lines-california"
	},
	{
		"id": "question:total-loss-how-long-must-insurer-renew-california",
		"kind": "question",
		"name": "My house was destroyed. How long does my insurer have to keep renewing while I rebuild?",
		"recordPath": "/questions/total-loss-how-long-must-insurer-renew-california"
	},
	{
		"id": "question:underinsured-motorist-paid-nothing-california",
		"kind": "question",
		"name": "Why did my California underinsured motorist coverage pay nothing?",
		"recordPath": "/questions/underinsured-motorist-paid-nothing-california"
	},
	{
		"id": "question:was-the-driver-of-my-car-covered-california",
		"kind": "question",
		"name": "My insurer says the person driving my car was not covered. Can it say that?",
		"recordPath": "/questions/was-the-driver-of-my-car-covered-california"
	},
	{
		"id": "question:what-a-general-liability-policy-excludes",
		"kind": "question",
		"name": "What does a general liability policy exclude, and which exclusions have a way back in?",
		"recordPath": "/questions/what-a-general-liability-policy-excludes"
	},
	{
		"id": "question:what-an-anti-harassment-policy-must-contain",
		"kind": "question",
		"name": "What does an anti-harassment policy actually have to contain, and how much of that is required?",
		"recordPath": "/questions/what-an-anti-harassment-policy-must-contain"
	},
	{
		"id": "question:what-backs-a-citizens-policy-florida",
		"kind": "question",
		"name": "Citizens is run by the state. What stands behind my policy, and can I be charged more after a hurricane?",
		"recordPath": "/questions/what-backs-a-citizens-policy-florida"
	},
	{
		"id": "question:what-can-my-auto-policy-exclude-california",
		"kind": "question",
		"name": "What is a California auto liability policy actually allowed to exclude?",
		"recordPath": "/questions/what-can-my-auto-policy-exclude-california"
	},
	{
		"id": "question:what-controls-will-a-cyber-insurer-ask-about",
		"kind": "question",
		"name": "What security controls will a cyber insurer ask about, and where do those questions come from?",
		"recordPath": "/questions/what-controls-will-a-cyber-insurer-ask-about"
	},
	{
		"id": "question:what-fair-plan-does-not-cover-california",
		"kind": "question",
		"name": "What does a California FAIR Plan policy not cover?",
		"recordPath": "/questions/what-fair-plan-does-not-cover-california"
	},
	{
		"id": "question:what-happens-if-i-have-no-workers-comp-california",
		"kind": "question",
		"name": "What actually happens if my business has no workers' compensation in California?",
		"recordPath": "/questions/what-happens-if-i-have-no-workers-comp-california"
	},
	{
		"id": "question:what-is-a-preliminary-report-california",
		"kind": "question",
		"name": "Is the preliminary report a search of my title, and are its exceptions problems being fixed?",
		"recordPath": "/questions/what-is-a-preliminary-report-california"
	},
	{
		"id": "question:what-makes-a-harassment-complaint-process-adequate",
		"kind": "question",
		"name": "We have a harassment complaint process. What makes it adequate rather than just present?",
		"recordPath": "/questions/what-makes-a-harassment-complaint-process-adequate"
	},
	{
		"id": "question:what-mfa-and-tested-backups-actually-have-to-mean",
		"kind": "question",
		"name": "The application asks whether we have MFA and tested backups. What do those answers actually have to mean?",
		"recordPath": "/questions/what-mfa-and-tested-backups-actually-have-to-mean"
	},
	{
		"id": "question:what-special-form-property-coverage-excludes",
		"kind": "question",
		"name": "My property policy says Special Form. What does that actually cover, and what is carved out?",
		"recordPath": "/questions/what-special-form-property-coverage-excludes"
	},
	{
		"id": "question:where-does-my-condo-unit-legally-end-california",
		"kind": "question",
		"name": "Where does my condominium unit legally end, and what is on the other side of that line?",
		"recordPath": "/questions/where-does-my-condo-unit-legally-end-california"
	},
	{
		"id": "question:which-affordability-safe-harbour-are-we-using",
		"kind": "question",
		"name": "Which affordability safe harbour is our health contribution measured against, and does the choice change the answer?",
		"recordPath": "/questions/which-affordability-safe-harbour-are-we-using"
	},
	{
		"id": "question:who-maintains-exclusive-use-balcony-california",
		"kind": "question",
		"name": "Who maintains a balcony or patio that is exclusive use common area?",
		"recordPath": "/questions/who-maintains-exclusive-use-balcony-california"
	},
	{
		"id": "question:who-pays-my-defence-costs-as-a-director",
		"kind": "question",
		"name": "I have been sued as a director. Will the company pay my defence costs, and when?",
		"recordPath": "/questions/who-pays-my-defence-costs-as-a-director"
	},
	{
		"id": "question:who-sets-california-workers-comp-rates",
		"kind": "question",
		"name": "California just announced a workers' comp rate increase. Does that mean my premium goes up?",
		"recordPath": "/questions/who-sets-california-workers-comp-rates"
	},
	{
		"id": "question:why-hasnt-escrow-disbursed-my-closing-funds-california",
		"kind": "question",
		"name": "My closing funds have arrived at escrow. Why has nothing been disbursed yet?",
		"recordPath": "/questions/why-hasnt-escrow-disbursed-my-closing-funds-california"
	},
	{
		"id": "question:why-is-my-whole-business-on-one-class-code",
		"kind": "question",
		"name": "My employees do completely different jobs. Why is the whole business on one workers' comp class code?",
		"recordPath": "/questions/why-is-my-whole-business-on-one-class-code"
	},
	{
		"id": "question:why-jewelry-claim-paid-so-little",
		"kind": "question",
		"name": "Why did my policy pay so little for stolen jewellery when my contents limit is large?",
		"recordPath": "/questions/why-jewelry-claim-paid-so-little"
	},
	{
		"id": "question:workers-comp-and-employers-liability-difference",
		"kind": "question",
		"name": "If I already have workers compensation, why does the policy also have employers liability?",
		"recordPath": "/questions/workers-comp-and-employers-liability-difference"
	},
	{
		"id": "question:workers-comp-audit-bill-after-policy-ended",
		"kind": "question",
		"name": "Why did I get a bill after my workers compensation policy ended?",
		"recordPath": "/questions/workers-comp-audit-bill-after-policy-ended"
	},
	{
		"id": "question:workers-comp-class-codes",
		"kind": "question",
		"name": "How do workers compensation class codes affect a quote?",
		"recordPath": "/questions/workers-comp-class-codes"
	}
];
