import { randomUUID } from 'node:crypto';
import { GENERATED_SUBJECTS } from './subjects.generated.ts';
import type { VerdictFlag } from './submissions.ts';
import { verdictFlags } from './submissions.ts';

/**
 * Threads: the conversation layer, and why it is not the case-report layer.
 *
 * `BIRCH.md` section 5 sets out the split and it is the whole design. A case
 * report is a structured account, read by a moderator before it appears, and
 * published as a file in the repository with version history and a reviewable
 * diff. A thread is a conversation. Nobody replies to a question and waits two
 * days for a commit, so posts appear when they are written.
 *
 * That difference changes one rule completely, and getting this wrong would
 * quietly break the only rule that survives the crossing from the Record.
 *
 * ON A SUBMISSION, A VERDICT PHRASE IS A FLAG. A moderator reads it before
 * anybody else does, so flagging is enough, and it must only flag: "the adjuster
 * said it should have been covered" is a report of what somebody said, which is
 * exactly the kind of fact this site wants, and rejecting it silently would cost
 * a real account.
 *
 * ON A THREAD POST, THE SAME PHRASE HAS TO BLOCK. Nothing reads it first. If it
 * saves, it is published, and `COMMONS.md` section 3 - nobody publishes a view
 * on whether a claim should have been paid - would hold on one layer of this
 * property and not the other. So the post is refused, and the writer is shown
 * the phrase, why it tripped, and the sentence that would carry the same
 * information without the verdict. Teaching the norm at the point of writing is
 * also simply better than removing it afterwards, when somebody has already
 * read it.
 *
 * The false positives are the cost, and they are paid deliberately: on a
 * conversation the writer is still at the keyboard and can rephrase in ten
 * seconds. On a twenty-minute structured form they are not.
 */

export interface Subject {
	id: string;
	kind: 'company' | 'coverage' | 'question';
	name: string;
	recordPath: string;
}

/**
 * What a thread may be about: exactly what the evidence layer publishes.
 *
 * Free-text topics are how a forum ends up with eleven spellings of one insurer
 * and no way to show a reader everything said about it. Generated by
 * `scripts/sync-subjects.mjs` and checked in; `verify-threads.mjs` fails when
 * the file is stale.
 */
export const SUBJECTS: Subject[] = GENERATED_SUBJECTS;

const BY_ID = new Map(SUBJECTS.map((s) => [s.id, s]));

export function subject(id: string): Subject | null {
	return BY_ID.get(id) ?? null;
}

export const LIMITS = {
	title: { min: 15, max: 140 },
	body: { min: 40, max: 4000 },
} as const;

export interface FieldError {
	field: string;
	message: string;
}

/**
 * The line every post carries, and the reason the forum is worth reading.
 *
 * It is the sentence the Record's eleven worked examples already carry in their
 * `decidedBy` field, and `BIRCH.md` makes it the model for the whole property.
 * A forum of strangers declaring what should have been covered is worth nothing
 * to anybody. A record of people saying what happened, what turned on it, and
 * who decided, is worth a great deal.
 */
export const STANDING_LINE = 'No authority decided this. It is illustrative only.';

/** How a verdict-shaped sentence can usually be said without the verdict. */
export const REPHRASE_GUIDANCE =
	'Say what happened and who decided it, rather than whether the decision was right. ' +
	'"The adjuster denied it citing the earth movement exclusion" carries everything ' +
	'"it should have been covered" carries, and it is checkable.';

function trimmed(input: Record<string, string>, field: string): string {
	return (input[field] ?? '').replace(/\r\n/g, '\n').trim();
}

function lengthProblem(value: string, limits: { min: number; max: number }, noun: string): string | null {
	if (value.length < limits.min) {
		return `${noun} is ${value.length} characters. It needs at least ${limits.min}, or nobody can tell what it is about.`;
	}
	if (value.length > limits.max) {
		return `${noun} is ${value.length} characters, and the limit is ${limits.max}. Anything longer is a case report rather than a post - use Contribute.`;
	}
	return null;
}

export interface ThreadDraftInput {
	subjectId: string;
	title: string;
	body: string;
}

export function validateNewThread(input: Record<string, string>): {
	errors: FieldError[];
	verdicts: VerdictFlag[];
	draft: ThreadDraftInput | null;
} {
	const errors: FieldError[] = [];
	const subjectId = trimmed(input, 'subjectId');
	const title = trimmed(input, 'title');
	const body = trimmed(input, 'body');

	if (!subjectId) {
		errors.push({ field: 'subjectId', message: 'Choose what this thread is about.' });
	} else if (!subject(subjectId)) {
		/* Not a validation nicety. A thread on a subject with no page is a thread
		   nobody arriving from the evidence layer will ever find. */
		errors.push({
			field: 'subjectId',
			message: 'That subject is not one this site has a page for, so a thread on it would be unreachable.',
		});
	}

	const titleProblem = lengthProblem(title, LIMITS.title, 'The title');
	if (titleProblem) errors.push({ field: 'title', message: titleProblem });
	else if (!/[a-z]/i.test(title)) errors.push({ field: 'title', message: 'The title needs words in it.' });

	const bodyProblem = lengthProblem(body, LIMITS.body, 'The post');
	if (bodyProblem) errors.push({ field: 'body', message: bodyProblem });

	const verdicts = verdictFlags(`${title}\n${body}`);
	for (const flag of verdicts) {
		errors.push({
			field: verdictFlags(title).some((f) => f.phrase === flag.phrase) ? 'title' : 'body',
			message: `"${flag.phrase}" ${flag.why}, and a post is published as you write it, so it cannot say that. ${REPHRASE_GUIDANCE}`,
		});
	}

	return {
		errors,
		verdicts,
		draft: errors.length === 0 ? { subjectId, title, body } : null,
	};
}

export function validateReply(input: Record<string, string>): {
	errors: FieldError[];
	verdicts: VerdictFlag[];
	body: string | null;
} {
	const errors: FieldError[] = [];
	const body = trimmed(input, 'body');

	const problem = lengthProblem(body, LIMITS.body, 'The reply');
	if (problem) errors.push({ field: 'body', message: problem });

	const verdicts = verdictFlags(body);
	for (const flag of verdicts) {
		errors.push({
			field: 'body',
			message: `"${flag.phrase}" ${flag.why}, and a reply is published as you write it, so it cannot say that. ${REPHRASE_GUIDANCE}`,
		});
	}

	return { errors, verdicts, body: errors.length === 0 ? body : null };
}

export const newThreadId = () => randomUUID();
export const newPostId = () => randomUUID();

/**
 * How a contributor is shown on a post.
 *
 * An account is not a byline: somebody who has never set a display name is
 * shown as a reader with no name rather than as their email address, which is
 * the mistake that turns a forum into a spam list. A verified professional is
 * shown as one, because that is the whole point of verifying them - but the
 * badge names the register the licence was checked against, not just the role,
 * so a reader can go and check it themselves.
 */
export function byline(account: {
	displayName: string;
	kind: string;
	license?: { number: string; authority: string };
}): { name: string; role: string | null } {
	const name = account.displayName.trim() || 'A reader, unnamed';
	if (account.kind === 'reader' || !account.license) return { name, role: null };
	return {
		name,
		role: `${account.kind}, ${account.license.authority} licence ${account.license.number}`,
	};
}
